export default [
  {
    "Rank ": 1,
    "Name ": "Jeff Bezos",
    "Age ": "57",
    "Residence ": "Seattle",
    "Work ": "Founder and Executive Chair: Amazon (AMZN)",
    "Net Worth ": "$177 billion",
    "Stake ": "Amazon Ownership Stake: 11% ($174 billion)",
    "Other Assets ":
      "Blue Origin ($7.15 billion private assets), The Washington Post ($250 million private assets), and $9.75 billion in cash",
  },
  {
    "Rank ": 2,
    "Name ": "Elon Musk",
    "Age ": "50",
    "Residence ": "Austin, Texas",
    "Work ": "Co-founder and CEO: Tesla (TSLA)",
    "Net Worth ": "$151 billion",
    "Stake ": "Tesla Ownership Stake: 20% ($114 billion)",
    "Other Assets ":
      "Space Exploration Technologies ($29.8 billion private assets) and The Boring Company ($101 million private assets)",
  },
  {
    "Rank ": 3,
    "Name ": "Bernard Arnault",
    "Age ": "72",
    "Residence ": "Paris",
    "Work ": "CEO and Chair: LVMH (LVMUY)",
    "Net Worth ": "$150 billion",
    "Stake ": "Christian Dior Ownership Stake: 97.5% ($109 billion)",
    "Other Assets ":
      "Moelis & Company equity ($21.4 billion public assets), Hermès equity ($2.23 billion public assets), Carrefour equity ($1.26 billion public assets), and $4.50 billion in cash",
  },
  {
    "Rank ": 4,
    "Name ": "Bill Gates",
    "Age ": "65",
    "Residence ": "Medina, Washington",
    "Work ": "Cofounder: Microsoft Corp. (MSFT)",
    "Net Worth ": "$124\xa0billion",
    "Stake ": "Microsoft Ownership Stake: 1.3% ($25.8 billion)",
    "Other Assets ":
      "Canadian National Railway equity ($11.8 billion public asset), John Deere equity ($11.8 billion public asset), Republic Services equity ($11.1 billion public asset), Ecolab equity ($6.59 billion public asset), Givaudan equity ($4.39 billion public asset), FEMSA equity ($2.22 billion public asset), Waste Management equity ($1.93 billion public asset), Berkshire Hathaway equity ($1.72 billion public asset), AutoNation equity ($1.67 billion public asset), Diageo equity ($1.56 billion public asset), Arch Capital Group equity ($1.39 billion public asset), Sika AG equity ($1.26 billion public asset), Signet Jewelers equity ($760 million public asset), Televisa equity ($300 million public asset), Vroom equity ($260 million public asset), Western Asset/Claymore Inflation-Linked Opportunities & Income Fund equity ($229.4 million public total assets), Liberty Global equity ($225 million public asset), Fomento de Construcciones y Contratas equity ($187 million public asset), Otter Tail Corporation equity ($160 million public asset), Coca-Cola FEMSA equity ($121 million public asset), Owens Corning equity ($38.4 million public asset), and $57.2 billion in cash",
  },
  {
    "Rank ": 5,
    "Name ": "Mark Zuckerberg",
    "Age ": "37",
    "Residence ": "Palo Alto, Calif.",
    "Work ": "Co-founder, CEO, and Chair: Facebook (FB)",
    "Net Worth ": "$97 billion",
    "Stake ": "Facebook Ownership Stake: 13% ($115 billion)",
    "Other Assets ": "$2.93 billion in cash and $225 million in real estate",
  },
  {
    "Rank ": 6,
    "Name ": "Warren Buffett",
    "Age ": "90",
    "Residence ": "Omaha, Nebraska",
    "Work ": "CEO: Berkshire Hathaway (BRK.A)",
    "Net Worth ": "$96 billion",
    "Stake ":
      "Berkshire Hathaway Ownership Stake: 38.001% ($98.503 billion total)",
    "Other Assets ":
      "Wells Fargo & Co. equity ($76.6 million public assets), U.S. Bancorp equity ($50.2 million public assets), Seritage Growth Properties equity ($38 million public assets), and $1.05 billion in cash",
  },
  {
    "Rank ": 7,
    "Name ": "Larry Ellison",
    "Age ": "76",
    "Residence ": "Lanai, Hawaii",
    "Work ": "Co-founder, CTO, and Chair: Oracle (ORCL)",
    "Net Worth ": "$93 billion",
    "Stake ": "Oracle Ownership Stake: 35.4% ($61.8 billion)",
    "Other Assets ":
      "Tesla equity ($10.1 billion public assets) and $14.9 billion in cash",
  },
  {
    "Rank ": 8,
    "Name ": "Larry Page",
    "Age ": "48",
    "Residence ": "Palo Alto, California",
    "Work ": "Co-founder and Board Member: Alphabet (GOOG)",
    "Net Worth ": "$91.5 billion",
    "Stake ": "Alphabet Ownership Stake: 6% ($89.7 billion total)",
    "Other Assets ": "$12.6 billion in cash",
  },
  {
    "Rank ": 9,
    "Name ": "Sergey Brin",
    "Age ": "47",
    "Residence ": "Los Altos, California",
    "Work ": "Co-founder and Board Member: Alphabet (GOOG)",
    "Net Worth ": "$89 billion\ufeff\ufeff",
    "Stake ": "Alphabet Ownership Stake: 5% ($86.2 billion total)",
    "Other Assets ": "$12.7 billion in cash\ufeff\ufeff",
  },
  {
    "Rank ": 10,
    "Name ": "Mukesh Ambani",
    "Age ": "64",
    "Residence ": "Mumbai, India",
    "Work ": "Chair and Managing Director: Reliance Industries",
    "Net Worth ": "$84.5 billion",
    "Stake ": "Reliance Industries Ownership Stake: 42% ($73.79 billion total)",
    "Other Assets ":
      "Mumbai residential property ($410 million private assets) and $1.60 billion in cash",
  },
];
